feat: implement scan matrix for mobile
agritheory/beam pull request #167
Opened 2024-09-06 10:17 UTC by Alchez

Closes #158

2024-09-06 10:23 UTC, Alchez commented
@agritheory I've added a `scan.ts` composable that can be manually used within each component. Currently it sets up the list-form context based on the current route's doctype (which I've defined in the route config).

There's a few things to work out still:
- [ ] **Form data:** Frappe uses `cur_frm.doc` to expose form data directly into the browser. Since we're manually using the composable, I'm wondering if we should just fetch and pass the form data to the composable to use.
- [ ] **Form actions:** The base `cur_frm` namespace also performs actions like adding/removing child table rows, refreshing fields, etc. We might want to re-think that in the mobile context since we're using Vue.

2024-09-13 12:38 UTC, agritheory requested changes
@Alchez I think you've gotten a head start on the reviewed changes before I submitted this. Let me know when to re-review.

2024-09-13 12:38 UTC, agritheory commented on beam/www/beam/routes.ts
> +		meta: { doctype: 'Purchase Order', view: 'list', requiresAuth: true },
'Purchase Receipt'

2024-09-13 12:38 UTC, agritheory commented on beam/www/beam/scan.ts
> +				let child = cur_frm.add_child('items', field.context)
We need to reimplement a helper for this that uses Pinia

2024-09-13 12:50 UTC, Alchez commented
@agritheory There's a couple of things left to do here:
- [ ] Make sure that adding a new row mirrors the API calls made in Frappe's forms
- [ ] Add an ability to save changes on the client and have it update the database via the API

And maybe more in case I've missed anything. But you can give it a fresh review until I can get to those.

2024-09-17 11:43 UTC, Alchez commented
@agritheory I made another pass at this, and I think I'll need to brainstorm a couple of things here:

- **Adding new rows:**
  - Whenever a scan outputs a new row in the table, we need to figure out a way to bootstrap an empty row and then add details on top of it.
  - Frappe uses the `frm.add_child` and `doc.append()` APIS in the client and server respectively to build the empty rows, and then update any user inputs onto it.
  - Should we consider adding default empty row templates (for ALL child tables?) in the initial server context that'll let us easily create rows?
- **Component layout:**
  - I'm trying to figure out a proper layout for the components in the application layer, and I've created a diagram that should help visualise how the different elements would work. Does it make sense for you?

![image](https://github.com/user-attachments/assets/fbba6300-4887-4011-8c7d-db3fca4ecdab)

2024-09-17 13:08 UTC, agritheory commented
> Whenever a scan outputs a new row in the table, we need to figure out a way to bootstrap an empty row and then add details on top of it.

I think having a helper function that add a new object with the keys is the thing to do here. We know the keys from the Type. Passing the entire array to the server to add a row is not the correct solution.

> Diagram

In the root component should be navigation, scan input and the router view. The Pinia store is instantiated here and only here; it is accessed via composable in the nested views like WorkOrder, Transfer and Ship

2024-09-18 10:55 UTC, Alchez commented
@agritheory Okay, I've setup the scan handler class and the Pinia store to be able to work across views. I think the only thing remaining task here is to add a 'Save' element that will allow passing the changes to the database. How do you think that should be handled?

Also, for the "add new row" problem, it seems like most keys aren't required when you're adding a child table row. So I was able to get away with simply adding the item/barcode-related keys and letting Frappe handle the rest. I'm sure this logic will need to be revisited later, but it should be good enough for the doctypes we're using right now.

2024-09-18 15:26 UTC, agritheory approved these changes
Let's get this merged so we can incorporate state management in other contexts as well. Looks great.

2024-09-18 15:26 UTC, merged