Transfer work order
agritheory/beam pull request #172
Opened 2024-09-13 16:45 UTC by lauty95

I created Transfer component which show `requiredItems` from data fetched from a Work Order

![Captura de pantalla 2024-09-13 a la(s) 1 28 28 p  m](https://github.com/user-attachments/assets/5f7b389e-8dfa-40d8-acf7-a8de48b41181)

2024-09-17 08:46 UTC, Alchez requested changes

2024-09-17 08:46 UTC, Alchez commented on beam/www/beam/index.ts
> +		component: Demand,
I think it may have shown up from a bad merge, but this version without the `meta` information is safe to remove

2024-09-17 08:46 UTC, Alchez commented on beam/www/beam/pages/WorkOrder.vue
> +const requiredItems = ref<ListTransferItem[]>([])
I don't think this is being used anywhere, but ignore if this is WIP

2024-09-17 08:46 UTC, Alchez commented on yarn.lock
Since Frappe apps work off of Yarn, I think you might want to regenerate this using `yarn install` instead

2024-09-17 13:20 UTC, agritheory commented on beam/www/beam/components/Transfer.vue
> +        <table class="item-table">
@lauty95 Can you refactor this to use ListView and ListItem

2024-09-19 20:25 UTC, merged

2024-09-19 20:25 UTC, agritheory commented
@lauty95 merged into mobile_v15_work_order_refactor