feat: handle scanning of non-handling units
agritheory/beam pull request #18
Opened 2023-06-01 06:40 UTC by Alchez

Fixes #7

2023-06-01 11:35 UTC, agritheory requested changes
Maybe worth having a conversation about best practices for setting rows and individual values in child tables. I have conflicting opinions.

2023-06-01 11:35 UTC, agritheory commented on beam/public/js/scan/scan.js
> +			frappe.ui.form.handlers[cur_frm.fields_dict.items.df.options].uom?.map(r => {
I think we want to remove this line

2023-06-02 06:06 UTC, Alchez commented on beam/public/js/scan/scan.js
> +			frappe.ui.form.handlers[cur_frm.fields_dict.items.df.options].uom?.map(r => {
I've removed that particular line, but we have a couple more instances that it's used. Should we remove those as well?

https://github.com/agritheory/beam/blob/54f6766ca9d7c6f42bac78573896370b70ff47b6/beam/public/js/scan/scan.js#L130-L134

https://github.com/agritheory/beam/blob/54f6766ca9d7c6f42bac78573896370b70ff47b6/beam/public/js/scan/scan.js#L177-L181

2023-06-02 06:09 UTC, Alchez commented on beam/beam/scan/__init__.py
> +			pass
@agritheory I've added a comment for how this could be handled, but I'm not sure about the implementation detail you prefer

2023-06-02 10:02 UTC, agritheory commented on beam/public/js/scan/scan.js
> +			frappe.ui.form.handlers[cur_frm.fields_dict.items.df.options].uom?.map(r => {
Yes please, I think they're also no longer required.

2023-06-02 10:03 UTC, agritheory commented on beam/beam/scan/__init__.py
> +			pass
Let's match what ERPNext is doing as closely as we can. It probably makes sense to pass the stock entry type in the form context.

2023-06-02 10:05 UTC, Alchez commented on beam/beam/scan/__init__.py
> +			pass
Should we enforce having the user set a purpose before they scan a barcode/HU then?

2023-06-02 10:07 UTC, agritheory commented on beam/beam/scan/__init__.py
> +			pass
Let's use a fallback of 'Material Transfer' instead; not correct, just least wrong.

2023-06-06 06:56 UTC, Alchez commented
@agritheory, this one is ready to be reviewed

2023-06-13 17:16 UTC, agritheory commented on beam/public/js/scan/scan.js
>  					if (cur_frm.doc.operation && cur_frm.doc.operation.includes('Mixing - ')) row.required_qty = row.stock_qty = 0
Let's remove this reference to Operation - this is customer specific code

2023-06-15 14:06 UTC, merged