feat: add config to ignore drop shipped items in demand
agritheory/beam pull request #208
Opened 2024-10-15 15:18 UTC by HKuz

Closes #183 

Refactored the PR to branch off the `receiving_demand` branch to leverage that branch's queries.

2024-10-16 14:19 UTC, agritheory commented
@HKuz Try using a dataclass to define the types for Demand and Allocation tables to defeat this mypy error

2024-10-21 18:47 UTC, agritheory requested changes
There has to be another way to do this, bracket syntax is terrible to read.
Try it this way: https://github.com/frappe/frappe/blob/develop/frappe/__init__.py#L56

2024-10-21 18:57 UTC, HKuz commented
@agritheory okay - I'll try maybe a mixin of TypedDict and _dict, but that was the core of most of the issues: the TypedDict object didn't support dot notation. (We may want to tighten some of the allowed types for the keys, too - the most recent set of errors were because a key could be a str or float, then we try to add/subtract/etc with it and mypy complained. I can get rid of the errors with casting, but that's also ugly.

2024-10-22 19:45 UTC, agritheory approved these changes

2024-10-22 19:45 UTC, merged