Mobile v15 metadata demand
agritheory/beam pull request #228
Opened 2024-11-21 16:57 UTC by lauty95

Added to sqlite:
* production_item
* bom_no
* source_warehouse (of each item of work order)

That data was added to demand.vue (old transfer.vue) and shown like receive.vue

![Captura de pantalla 2024-11-21 a la(s) 1 55 32 p  m](https://github.com/user-attachments/assets/e44420df-61eb-400f-ae4e-39eaac28daa6)

2024-11-22 06:08 UTC, Alchez requested changes

2024-11-22 06:08 UTC, Alchez commented on beam/www/beam/pages/Demand.vue
> +			row.count = { count: row.allocated_qty, of: `${row.total_required_qty}` }
@lauty95 both the `count` and `of` values need to be a number. I'll look into adding type-hints for this file.

2024-11-22 13:34 UTC, lauty95 commented
@Alchez
I added types of Demand and Receive and used it on Demand.vue Receive.vue and Ship.vue.

I had to change the way to transform and push the data to ListView.

Tell me if it is ok to you or If I should do different.
Thanks!

2024-11-25 09:23 UTC, Alchez commented
@lauty95 The changes look good! I also added a small commit that fixes the mixed indentation in the Vue files.

2024-11-25 12:58 UTC, merged